# Generated by Django 3.0.5 on 2020-04-20 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('creator', models.TextField(blank=True, max_length=255)),
                ('people', models.TextField(blank=True, max_length=255)),
                ('resources', models.TextField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('location', models.TextField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_modification', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('available_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('limit_available', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
